/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_XQ_FILES           60
#define MMAP_XQ_CHECKSUM        0x7C76

enum MMAP_XQ_LISTS {
    MMAP_XQ_FXQ0_P3 = 0,        /*!< fxq0.p3 */
    MMAP_XQ_FXQ1_P3 = 1,        /*!< fxq1.p3 */
    MMAP_XQ_FXQ10_P3 = 2,        /*!< fxq10.p3 */
    MMAP_XQ_FXQ11_P3 = 3,        /*!< fxq11.p3 */
    MMAP_XQ_FXQ12_P3 = 4,        /*!< fxq12.p3 */
    MMAP_XQ_FXQ13_P3 = 5,        /*!< fxq13.p3 */
    MMAP_XQ_FXQ14_P3 = 6,        /*!< fxq14.p3 */
    MMAP_XQ_FXQ15_P3 = 7,        /*!< fxq15.p3 */
    MMAP_XQ_FXQ16_P3 = 8,        /*!< fxq16.p3 */
    MMAP_XQ_FXQ17_P3 = 9,        /*!< fxq17.p3 */
    MMAP_XQ_FXQ18_P3 = 10,        /*!< fxq18.p3 */
    MMAP_XQ_FXQ19_P3 = 11,        /*!< fxq19.p3 */
    MMAP_XQ_FXQ2_P3 = 12,        /*!< fxq2.p3 */
    MMAP_XQ_FXQ20_P3 = 13,        /*!< fxq20.p3 */
    MMAP_XQ_FXQ21_P3 = 14,        /*!< fxq21.p3 */
    MMAP_XQ_FXQ22_P3 = 15,        /*!< fxq22.p3 */
    MMAP_XQ_FXQ23_P3 = 16,        /*!< fxq23.p3 */
    MMAP_XQ_FXQ24_P3 = 17,        /*!< fxq24.p3 */
    MMAP_XQ_FXQ25_P3 = 18,        /*!< fxq25.p3 */
    MMAP_XQ_FXQ26_P3 = 19,        /*!< fxq26.p3 */
    MMAP_XQ_FXQ27_P3 = 20,        /*!< fxq27.p3 */
    MMAP_XQ_FXQ28_P3 = 21,        /*!< fxq28.p3 */
    MMAP_XQ_FXQ29_P3 = 22,        /*!< fxq29.p3 */
    MMAP_XQ_FXQ3_P3 = 23,        /*!< fxq3.p3 */
    MMAP_XQ_FXQ30_P3 = 24,        /*!< fxq30.p3 */
    MMAP_XQ_FXQ31_P3 = 25,        /*!< fxq31.p3 */
    MMAP_XQ_FXQ32_P3 = 26,        /*!< fxq32.p3 */
    MMAP_XQ_FXQ33_P3 = 27,        /*!< fxq33.p3 */
    MMAP_XQ_FXQ34_P3 = 28,        /*!< fxq34.p3 */
    MMAP_XQ_FXQ35_P3 = 29,        /*!< fxq35.p3 */
    MMAP_XQ_FXQ36_P3 = 30,        /*!< fxq36.p3 */
    MMAP_XQ_FXQ37_P3 = 31,        /*!< fxq37.p3 */
    MMAP_XQ_FXQ38_P3 = 32,        /*!< fxq38.p3 */
    MMAP_XQ_FXQ39_P3 = 33,        /*!< fxq39.p3 */
    MMAP_XQ_FXQ4_P3 = 34,        /*!< fxq4.p3 */
    MMAP_XQ_FXQ40_P3 = 35,        /*!< fxq40.p3 */
    MMAP_XQ_FXQ41_P3 = 36,        /*!< fxq41.p3 */
    MMAP_XQ_FXQ42_P3 = 37,        /*!< fxq42.p3 */
    MMAP_XQ_FXQ43_P3 = 38,        /*!< fxq43.p3 */
    MMAP_XQ_FXQ44_P3 = 39,        /*!< fxq44.p3 */
    MMAP_XQ_FXQ45_P3 = 40,        /*!< fxq45.p3 */
    MMAP_XQ_FXQ46_P3 = 41,        /*!< fxq46.p3 */
    MMAP_XQ_FXQ47_P3 = 42,        /*!< fxq47.p3 */
    MMAP_XQ_FXQ48_P3 = 43,        /*!< fxq48.p3 */
    MMAP_XQ_FXQ49_P3 = 44,        /*!< fxq49.p3 */
    MMAP_XQ_FXQ5_P3 = 45,        /*!< fxq5.p3 */
    MMAP_XQ_FXQ50_P3 = 46,        /*!< fxq50.p3 */
    MMAP_XQ_FXQ51_P3 = 47,        /*!< fxq51.p3 */
    MMAP_XQ_FXQ52_P3 = 48,        /*!< fxq52.p3 */
    MMAP_XQ_FXQ53_P3 = 49,        /*!< fxq53.p3 */
    MMAP_XQ_FXQ54_P3 = 50,        /*!< fxq54.p3 */
    MMAP_XQ_FXQ55_P3 = 51,        /*!< fxq55.p3 */
    MMAP_XQ_FXQ56_P3 = 52,        /*!< fxq56.p3 */
    MMAP_XQ_FXQ57_P3 = 53,        /*!< fxq57.p3 */
    MMAP_XQ_FXQ58_P3 = 54,        /*!< fxq58.p3 */
    MMAP_XQ_FXQ59_P3 = 55,        /*!< fxq59.p3 */
    MMAP_XQ_FXQ6_P3 = 56,        /*!< fxq6.p3 */
    MMAP_XQ_FXQ7_P3 = 57,        /*!< fxq7.p3 */
    MMAP_XQ_FXQ8_P3 = 58,        /*!< fxq8.p3 */
    MMAP_XQ_FXQ9_P3 = 59,        /*!< fxq9.p3 */
};
