/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_NS_FILES           57
#define MMAP_NS_CHECKSUM        0x214D

enum MMAP_NS_LISTS {
    MMAP_NS_FNS0_P3 = 0,        /*!< fns0.p3 */
    MMAP_NS_FNS1_P3 = 1,        /*!< fns1.p3 */
    MMAP_NS_FNS10_P3 = 2,        /*!< fns10.p3 */
    MMAP_NS_FNS11_P3 = 3,        /*!< fns11.p3 */
    MMAP_NS_FNS12_P3 = 4,        /*!< fns12.p3 */
    MMAP_NS_FNS13_P3 = 5,        /*!< fns13.p3 */
    MMAP_NS_FNS14_P3 = 6,        /*!< fns14.p3 */
    MMAP_NS_FNS15_P3 = 7,        /*!< fns15.p3 */
    MMAP_NS_FNS16_P3 = 8,        /*!< fns16.p3 */
    MMAP_NS_FNS17_P3 = 9,        /*!< fns17.p3 */
    MMAP_NS_FNS18_P3 = 10,        /*!< fns18.p3 */
    MMAP_NS_FNS19_P3 = 11,        /*!< fns19.p3 */
    MMAP_NS_FNS2_P3 = 12,        /*!< fns2.p3 */
    MMAP_NS_FNS20_P3 = 13,        /*!< fns20.p3 */
    MMAP_NS_FNS21_P3 = 14,        /*!< fns21.p3 */
    MMAP_NS_FNS22_P3 = 15,        /*!< fns22.p3 */
    MMAP_NS_FNS23_P3 = 16,        /*!< fns23.p3 */
    MMAP_NS_FNS24_P3 = 17,        /*!< fns24.p3 */
    MMAP_NS_FNS25_P3 = 18,        /*!< fns25.p3 */
    MMAP_NS_FNS26_P3 = 19,        /*!< fns26.p3 */
    MMAP_NS_FNS27_P3 = 20,        /*!< fns27.p3 */
    MMAP_NS_FNS28_P3 = 21,        /*!< fns28.p3 */
    MMAP_NS_FNS29_P3 = 22,        /*!< fns29.p3 */
    MMAP_NS_FNS3_P3 = 23,        /*!< fns3.p3 */
    MMAP_NS_FNS30_P3 = 24,        /*!< fns30.p3 */
    MMAP_NS_FNS31_P3 = 25,        /*!< fns31.p3 */
    MMAP_NS_FNS32_P3 = 26,        /*!< fns32.p3 */
    MMAP_NS_FNS33_P3 = 27,        /*!< fns33.p3 */
    MMAP_NS_FNS34_P3 = 28,        /*!< fns34.p3 */
    MMAP_NS_FNS35_P3 = 29,        /*!< fns35.p3 */
    MMAP_NS_FNS36_P3 = 30,        /*!< fns36.p3 */
    MMAP_NS_FNS37_P3 = 31,        /*!< fns37.p3 */
    MMAP_NS_FNS38_P3 = 32,        /*!< fns38.p3 */
    MMAP_NS_FNS39_P3 = 33,        /*!< fns39.p3 */
    MMAP_NS_FNS4_P3 = 34,        /*!< fns4.p3 */
    MMAP_NS_FNS40_P3 = 35,        /*!< fns40.p3 */
    MMAP_NS_FNS41_P3 = 36,        /*!< fns41.p3 */
    MMAP_NS_FNS42_P3 = 37,        /*!< fns42.p3 */
    MMAP_NS_FNS43_P3 = 38,        /*!< fns43.p3 */
    MMAP_NS_FNS44_P3 = 39,        /*!< fns44.p3 */
    MMAP_NS_FNS45_P3 = 40,        /*!< fns45.p3 */
    MMAP_NS_FNS46_P3 = 41,        /*!< fns46.p3 */
    MMAP_NS_FNS47_P3 = 42,        /*!< fns47.p3 */
    MMAP_NS_FNS48_P3 = 43,        /*!< fns48.p3 */
    MMAP_NS_FNS49_P3 = 44,        /*!< fns49.p3 */
    MMAP_NS_FNS5_P3 = 45,        /*!< fns5.p3 */
    MMAP_NS_FNS50_P3 = 46,        /*!< fns50.p3 */
    MMAP_NS_FNS51_P3 = 47,        /*!< fns51.p3 */
    MMAP_NS_FNS52_P3 = 48,        /*!< fns52.p3 */
    MMAP_NS_FNS53_P3 = 49,        /*!< fns53.p3 */
    MMAP_NS_FNS54_P3 = 50,        /*!< fns54.p3 */
    MMAP_NS_FNS55_P3 = 51,        /*!< fns55.p3 */
    MMAP_NS_FNS56_P3 = 52,        /*!< fns56.p3 */
    MMAP_NS_FNS6_P3 = 53,        /*!< fns6.p3 */
    MMAP_NS_FNS7_P3 = 54,        /*!< fns7.p3 */
    MMAP_NS_FNS8_P3 = 55,        /*!< fns8.p3 */
    MMAP_NS_FNS9_P3 = 56,        /*!< fns9.p3 */
};
