/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_QL_FILES           113
#define MMAP_QL_CHECKSUM        0x7B4A

enum MMAP_QL_LISTS {
    MMAP_QL_QL1_P3 = 0,        /*!< ql1.p3 */
    MMAP_QL_QL10_P3 = 1,        /*!< ql10.p3 */
    MMAP_QL_QL100_P3 = 2,        /*!< ql100.p3 */
    MMAP_QL_QL101_P3 = 3,        /*!< ql101.p3 */
    MMAP_QL_QL102_P3 = 4,        /*!< ql102.p3 */
    MMAP_QL_QL103_P3 = 5,        /*!< ql103.p3 */
    MMAP_QL_QL104_P3 = 6,        /*!< ql104.p3 */
    MMAP_QL_QL105_P3 = 7,        /*!< ql105.p3 */
    MMAP_QL_QL106_P3 = 8,        /*!< ql106.p3 */
    MMAP_QL_QL107_P3 = 9,        /*!< ql107.p3 */
    MMAP_QL_QL108_P3 = 10,        /*!< ql108.p3 */
    MMAP_QL_QL109_P3 = 11,        /*!< ql109.p3 */
    MMAP_QL_QL11_P3 = 12,        /*!< ql11.p3 */
    MMAP_QL_QL110_P3 = 13,        /*!< ql110.p3 */
    MMAP_QL_QL111_P3 = 14,        /*!< ql111.p3 */
    MMAP_QL_QL112_P3 = 15,        /*!< ql112.p3 */
    MMAP_QL_QL113_P3 = 16,        /*!< ql113.p3 */
    MMAP_QL_QL12_P3 = 17,        /*!< ql12.p3 */
    MMAP_QL_QL13_P3 = 18,        /*!< ql13.p3 */
    MMAP_QL_QL14_P3 = 19,        /*!< ql14.p3 */
    MMAP_QL_QL15_P3 = 20,        /*!< ql15.p3 */
    MMAP_QL_QL16_P3 = 21,        /*!< ql16.p3 */
    MMAP_QL_QL17_P3 = 22,        /*!< ql17.p3 */
    MMAP_QL_QL18_P3 = 23,        /*!< ql18.p3 */
    MMAP_QL_QL19_P3 = 24,        /*!< ql19.p3 */
    MMAP_QL_QL2_P3 = 25,        /*!< ql2.p3 */
    MMAP_QL_QL20_P3 = 26,        /*!< ql20.p3 */
    MMAP_QL_QL21_P3 = 27,        /*!< ql21.p3 */
    MMAP_QL_QL22_P3 = 28,        /*!< ql22.p3 */
    MMAP_QL_QL23_P3 = 29,        /*!< ql23.p3 */
    MMAP_QL_QL24_P3 = 30,        /*!< ql24.p3 */
    MMAP_QL_QL25_P3 = 31,        /*!< ql25.p3 */
    MMAP_QL_QL26_P3 = 32,        /*!< ql26.p3 */
    MMAP_QL_QL27_P3 = 33,        /*!< ql27.p3 */
    MMAP_QL_QL28_P3 = 34,        /*!< ql28.p3 */
    MMAP_QL_QL29_P3 = 35,        /*!< ql29.p3 */
    MMAP_QL_QL3_P3 = 36,        /*!< ql3.p3 */
    MMAP_QL_QL30_P3 = 37,        /*!< ql30.p3 */
    MMAP_QL_QL31_P3 = 38,        /*!< ql31.p3 */
    MMAP_QL_QL32_P3 = 39,        /*!< ql32.p3 */
    MMAP_QL_QL33_P3 = 40,        /*!< ql33.p3 */
    MMAP_QL_QL34_P3 = 41,        /*!< ql34.p3 */
    MMAP_QL_QL35_P3 = 42,        /*!< ql35.p3 */
    MMAP_QL_QL36_P3 = 43,        /*!< ql36.p3 */
    MMAP_QL_QL37_P3 = 44,        /*!< ql37.p3 */
    MMAP_QL_QL38_P3 = 45,        /*!< ql38.p3 */
    MMAP_QL_QL39_P3 = 46,        /*!< ql39.p3 */
    MMAP_QL_QL4_P3 = 47,        /*!< ql4.p3 */
    MMAP_QL_QL40_P3 = 48,        /*!< ql40.p3 */
    MMAP_QL_QL41_P3 = 49,        /*!< ql41.p3 */
    MMAP_QL_QL42_P3 = 50,        /*!< ql42.p3 */
    MMAP_QL_QL43_P3 = 51,        /*!< ql43.p3 */
    MMAP_QL_QL44_P3 = 52,        /*!< ql44.p3 */
    MMAP_QL_QL45_P3 = 53,        /*!< ql45.p3 */
    MMAP_QL_QL46_P3 = 54,        /*!< ql46.p3 */
    MMAP_QL_QL47_P3 = 55,        /*!< ql47.p3 */
    MMAP_QL_QL48_P3 = 56,        /*!< ql48.p3 */
    MMAP_QL_QL49_P3 = 57,        /*!< ql49.p3 */
    MMAP_QL_QL5_P3 = 58,        /*!< ql5.p3 */
    MMAP_QL_QL50_P3 = 59,        /*!< ql50.p3 */
    MMAP_QL_QL51_P3 = 60,        /*!< ql51.p3 */
    MMAP_QL_QL52_P3 = 61,        /*!< ql52.p3 */
    MMAP_QL_QL53_P3 = 62,        /*!< ql53.p3 */
    MMAP_QL_QL54_P3 = 63,        /*!< ql54.p3 */
    MMAP_QL_QL55_P3 = 64,        /*!< ql55.p3 */
    MMAP_QL_QL56_P3 = 65,        /*!< ql56.p3 */
    MMAP_QL_QL57_P3 = 66,        /*!< ql57.p3 */
    MMAP_QL_QL58_P3 = 67,        /*!< ql58.p3 */
    MMAP_QL_QL59_P3 = 68,        /*!< ql59.p3 */
    MMAP_QL_QL6_P3 = 69,        /*!< ql6.p3 */
    MMAP_QL_QL60_P3 = 70,        /*!< ql60.p3 */
    MMAP_QL_QL61_P3 = 71,        /*!< ql61.p3 */
    MMAP_QL_QL62_P3 = 72,        /*!< ql62.p3 */
    MMAP_QL_QL63_P3 = 73,        /*!< ql63.p3 */
    MMAP_QL_QL64_P3 = 74,        /*!< ql64.p3 */
    MMAP_QL_QL65_P3 = 75,        /*!< ql65.p3 */
    MMAP_QL_QL66_P3 = 76,        /*!< ql66.p3 */
    MMAP_QL_QL67_P3 = 77,        /*!< ql67.p3 */
    MMAP_QL_QL68_P3 = 78,        /*!< ql68.p3 */
    MMAP_QL_QL69_P3 = 79,        /*!< ql69.p3 */
    MMAP_QL_QL7_P3 = 80,        /*!< ql7.p3 */
    MMAP_QL_QL70_P3 = 81,        /*!< ql70.p3 */
    MMAP_QL_QL71_P3 = 82,        /*!< ql71.p3 */
    MMAP_QL_QL72_P3 = 83,        /*!< ql72.p3 */
    MMAP_QL_QL73_P3 = 84,        /*!< ql73.p3 */
    MMAP_QL_QL74_P3 = 85,        /*!< ql74.p3 */
    MMAP_QL_QL75_P3 = 86,        /*!< ql75.p3 */
    MMAP_QL_QL76_P3 = 87,        /*!< ql76.p3 */
    MMAP_QL_QL77_P3 = 88,        /*!< ql77.p3 */
    MMAP_QL_QL78_P3 = 89,        /*!< ql78.p3 */
    MMAP_QL_QL79_P3 = 90,        /*!< ql79.p3 */
    MMAP_QL_QL8_P3 = 91,        /*!< ql8.p3 */
    MMAP_QL_QL80_P3 = 92,        /*!< ql80.p3 */
    MMAP_QL_QL81_P3 = 93,        /*!< ql81.p3 */
    MMAP_QL_QL82_P3 = 94,        /*!< ql82.p3 */
    MMAP_QL_QL83_P3 = 95,        /*!< ql83.p3 */
    MMAP_QL_QL84_P3 = 96,        /*!< ql84.p3 */
    MMAP_QL_QL85_P3 = 97,        /*!< ql85.p3 */
    MMAP_QL_QL86_P3 = 98,        /*!< ql86.p3 */
    MMAP_QL_QL87_P3 = 99,        /*!< ql87.p3 */
    MMAP_QL_QL88_P3 = 100,        /*!< ql88.p3 */
    MMAP_QL_QL89_P3 = 101,        /*!< ql89.p3 */
    MMAP_QL_QL9_P3 = 102,        /*!< ql9.p3 */
    MMAP_QL_QL90_P3 = 103,        /*!< ql90.p3 */
    MMAP_QL_QL91_P3 = 104,        /*!< ql91.p3 */
    MMAP_QL_QL92_P3 = 105,        /*!< ql92.p3 */
    MMAP_QL_QL93_P3 = 106,        /*!< ql93.p3 */
    MMAP_QL_QL94_P3 = 107,        /*!< ql94.p3 */
    MMAP_QL_QL95_P3 = 108,        /*!< ql95.p3 */
    MMAP_QL_QL96_P3 = 109,        /*!< ql96.p3 */
    MMAP_QL_QL97_P3 = 110,        /*!< ql97.p3 */
    MMAP_QL_QL98_P3 = 111,        /*!< ql98.p3 */
    MMAP_QL_QL99_P3 = 112,        /*!< ql99.p3 */
};
