/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_NS_FILES           102
#define MMAP_NS_CHECKSUM        0x5B81

enum MMAP_NS_LISTS {
    MMAP_NS_NS1_P3 = 0,        /*!< ns1.p3 */
    MMAP_NS_NS10_P3 = 1,        /*!< ns10.p3 */
    MMAP_NS_NS100_P3 = 2,        /*!< ns100.p3 */
    MMAP_NS_NS101_P3 = 3,        /*!< ns101.p3 */
    MMAP_NS_NS102_P3 = 4,        /*!< ns102.p3 */
    MMAP_NS_NS11_P3 = 5,        /*!< ns11.p3 */
    MMAP_NS_NS12_P3 = 6,        /*!< ns12.p3 */
    MMAP_NS_NS13_P3 = 7,        /*!< ns13.p3 */
    MMAP_NS_NS14_P3 = 8,        /*!< ns14.p3 */
    MMAP_NS_NS15_P3 = 9,        /*!< ns15.p3 */
    MMAP_NS_NS16_P3 = 10,        /*!< ns16.p3 */
    MMAP_NS_NS17_P3 = 11,        /*!< ns17.p3 */
    MMAP_NS_NS18_P3 = 12,        /*!< ns18.p3 */
    MMAP_NS_NS19_P3 = 13,        /*!< ns19.p3 */
    MMAP_NS_NS2_P3 = 14,        /*!< ns2.p3 */
    MMAP_NS_NS20_P3 = 15,        /*!< ns20.p3 */
    MMAP_NS_NS21_P3 = 16,        /*!< ns21.p3 */
    MMAP_NS_NS22_P3 = 17,        /*!< ns22.p3 */
    MMAP_NS_NS23_P3 = 18,        /*!< ns23.p3 */
    MMAP_NS_NS24_P3 = 19,        /*!< ns24.p3 */
    MMAP_NS_NS25_P3 = 20,        /*!< ns25.p3 */
    MMAP_NS_NS26_P3 = 21,        /*!< ns26.p3 */
    MMAP_NS_NS27_P3 = 22,        /*!< ns27.p3 */
    MMAP_NS_NS28_P3 = 23,        /*!< ns28.p3 */
    MMAP_NS_NS29_P3 = 24,        /*!< ns29.p3 */
    MMAP_NS_NS3_P3 = 25,        /*!< ns3.p3 */
    MMAP_NS_NS30_P3 = 26,        /*!< ns30.p3 */
    MMAP_NS_NS31_P3 = 27,        /*!< ns31.p3 */
    MMAP_NS_NS32_P3 = 28,        /*!< ns32.p3 */
    MMAP_NS_NS33_P3 = 29,        /*!< ns33.p3 */
    MMAP_NS_NS34_P3 = 30,        /*!< ns34.p3 */
    MMAP_NS_NS35_P3 = 31,        /*!< ns35.p3 */
    MMAP_NS_NS36_P3 = 32,        /*!< ns36.p3 */
    MMAP_NS_NS37_P3 = 33,        /*!< ns37.p3 */
    MMAP_NS_NS38_P3 = 34,        /*!< ns38.p3 */
    MMAP_NS_NS39_P3 = 35,        /*!< ns39.p3 */
    MMAP_NS_NS4_P3 = 36,        /*!< ns4.p3 */
    MMAP_NS_NS40_P3 = 37,        /*!< ns40.p3 */
    MMAP_NS_NS41_P3 = 38,        /*!< ns41.p3 */
    MMAP_NS_NS42_P3 = 39,        /*!< ns42.p3 */
    MMAP_NS_NS43_P3 = 40,        /*!< ns43.p3 */
    MMAP_NS_NS44_P3 = 41,        /*!< ns44.p3 */
    MMAP_NS_NS45_P3 = 42,        /*!< ns45.p3 */
    MMAP_NS_NS46_P3 = 43,        /*!< ns46.p3 */
    MMAP_NS_NS47_P3 = 44,        /*!< ns47.p3 */
    MMAP_NS_NS48_P3 = 45,        /*!< ns48.p3 */
    MMAP_NS_NS49_P3 = 46,        /*!< ns49.p3 */
    MMAP_NS_NS5_P3 = 47,        /*!< ns5.p3 */
    MMAP_NS_NS50_P3 = 48,        /*!< ns50.p3 */
    MMAP_NS_NS51_P3 = 49,        /*!< ns51.p3 */
    MMAP_NS_NS52_P3 = 50,        /*!< ns52.p3 */
    MMAP_NS_NS53_P3 = 51,        /*!< ns53.p3 */
    MMAP_NS_NS54_P3 = 52,        /*!< ns54.p3 */
    MMAP_NS_NS55_P3 = 53,        /*!< ns55.p3 */
    MMAP_NS_NS56_P3 = 54,        /*!< ns56.p3 */
    MMAP_NS_NS57_P3 = 55,        /*!< ns57.p3 */
    MMAP_NS_NS58_P3 = 56,        /*!< ns58.p3 */
    MMAP_NS_NS59_P3 = 57,        /*!< ns59.p3 */
    MMAP_NS_NS6_P3 = 58,        /*!< ns6.p3 */
    MMAP_NS_NS60_P3 = 59,        /*!< ns60.p3 */
    MMAP_NS_NS61_P3 = 60,        /*!< ns61.p3 */
    MMAP_NS_NS62_P3 = 61,        /*!< ns62.p3 */
    MMAP_NS_NS63_P3 = 62,        /*!< ns63.p3 */
    MMAP_NS_NS64_P3 = 63,        /*!< ns64.p3 */
    MMAP_NS_NS65_P3 = 64,        /*!< ns65.p3 */
    MMAP_NS_NS66_P3 = 65,        /*!< ns66.p3 */
    MMAP_NS_NS67_P3 = 66,        /*!< ns67.p3 */
    MMAP_NS_NS68_P3 = 67,        /*!< ns68.p3 */
    MMAP_NS_NS69_P3 = 68,        /*!< ns69.p3 */
    MMAP_NS_NS7_P3 = 69,        /*!< ns7.p3 */
    MMAP_NS_NS70_P3 = 70,        /*!< ns70.p3 */
    MMAP_NS_NS71_P3 = 71,        /*!< ns71.p3 */
    MMAP_NS_NS72_P3 = 72,        /*!< ns72.p3 */
    MMAP_NS_NS73_P3 = 73,        /*!< ns73.p3 */
    MMAP_NS_NS74_P3 = 74,        /*!< ns74.p3 */
    MMAP_NS_NS75_P3 = 75,        /*!< ns75.p3 */
    MMAP_NS_NS76_P3 = 76,        /*!< ns76.p3 */
    MMAP_NS_NS77_P3 = 77,        /*!< ns77.p3 */
    MMAP_NS_NS78_P3 = 78,        /*!< ns78.p3 */
    MMAP_NS_NS79_P3 = 79,        /*!< ns79.p3 */
    MMAP_NS_NS8_P3 = 80,        /*!< ns8.p3 */
    MMAP_NS_NS80_P3 = 81,        /*!< ns80.p3 */
    MMAP_NS_NS81_P3 = 82,        /*!< ns81.p3 */
    MMAP_NS_NS82_P3 = 83,        /*!< ns82.p3 */
    MMAP_NS_NS83_P3 = 84,        /*!< ns83.p3 */
    MMAP_NS_NS84_P3 = 85,        /*!< ns84.p3 */
    MMAP_NS_NS85_P3 = 86,        /*!< ns85.p3 */
    MMAP_NS_NS86_P3 = 87,        /*!< ns86.p3 */
    MMAP_NS_NS87_P3 = 88,        /*!< ns87.p3 */
    MMAP_NS_NS88_P3 = 89,        /*!< ns88.p3 */
    MMAP_NS_NS89_P3 = 90,        /*!< ns89.p3 */
    MMAP_NS_NS9_P3 = 91,        /*!< ns9.p3 */
    MMAP_NS_NS90_P3 = 92,        /*!< ns90.p3 */
    MMAP_NS_NS91_P3 = 93,        /*!< ns91.p3 */
    MMAP_NS_NS92_P3 = 94,        /*!< ns92.p3 */
    MMAP_NS_NS93_P3 = 95,        /*!< ns93.p3 */
    MMAP_NS_NS94_P3 = 96,        /*!< ns94.p3 */
    MMAP_NS_NS95_P3 = 97,        /*!< ns95.p3 */
    MMAP_NS_NS96_P3 = 98,        /*!< ns96.p3 */
    MMAP_NS_NS97_P3 = 99,        /*!< ns97.p3 */
    MMAP_NS_NS98_P3 = 100,        /*!< ns98.p3 */
    MMAP_NS_NS99_P3 = 101,        /*!< ns99.p3 */
};
