/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_QL_FILES           53
#define MMAP_QL_CHECKSUM        0x9BBA

enum MMAP_QL_LISTS {
    MMAP_QL_FQL0_P3 = 0,        /*!< fql0.p3 */
    MMAP_QL_FQL1_P3 = 1,        /*!< fql1.p3 */
    MMAP_QL_FQL10_P3 = 2,        /*!< fql10.p3 */
    MMAP_QL_FQL11_P3 = 3,        /*!< fql11.p3 */
    MMAP_QL_FQL12_P3 = 4,        /*!< fql12.p3 */
    MMAP_QL_FQL13_P3 = 5,        /*!< fql13.p3 */
    MMAP_QL_FQL14_P3 = 6,        /*!< fql14.p3 */
    MMAP_QL_FQL15_P3 = 7,        /*!< fql15.p3 */
    MMAP_QL_FQL16_P3 = 8,        /*!< fql16.p3 */
    MMAP_QL_FQL17_P3 = 9,        /*!< fql17.p3 */
    MMAP_QL_FQL18_P3 = 10,        /*!< fql18.p3 */
    MMAP_QL_FQL19_P3 = 11,        /*!< fql19.p3 */
    MMAP_QL_FQL2_P3 = 12,        /*!< fql2.p3 */
    MMAP_QL_FQL20_P3 = 13,        /*!< fql20.p3 */
    MMAP_QL_FQL21_P3 = 14,        /*!< fql21.p3 */
    MMAP_QL_FQL22_P3 = 15,        /*!< fql22.p3 */
    MMAP_QL_FQL23_P3 = 16,        /*!< fql23.p3 */
    MMAP_QL_FQL24_P3 = 17,        /*!< fql24.p3 */
    MMAP_QL_FQL25_P3 = 18,        /*!< fql25.p3 */
    MMAP_QL_FQL26_P3 = 19,        /*!< fql26.p3 */
    MMAP_QL_FQL27_P3 = 20,        /*!< fql27.p3 */
    MMAP_QL_FQL28_P3 = 21,        /*!< fql28.p3 */
    MMAP_QL_FQL29_P3 = 22,        /*!< fql29.p3 */
    MMAP_QL_FQL3_P3 = 23,        /*!< fql3.p3 */
    MMAP_QL_FQL30_P3 = 24,        /*!< fql30.p3 */
    MMAP_QL_FQL31_P3 = 25,        /*!< fql31.p3 */
    MMAP_QL_FQL32_P3 = 26,        /*!< fql32.p3 */
    MMAP_QL_FQL33_P3 = 27,        /*!< fql33.p3 */
    MMAP_QL_FQL34_P3 = 28,        /*!< fql34.p3 */
    MMAP_QL_FQL35_P3 = 29,        /*!< fql35.p3 */
    MMAP_QL_FQL36_P3 = 30,        /*!< fql36.p3 */
    MMAP_QL_FQL37_P3 = 31,        /*!< fql37.p3 */
    MMAP_QL_FQL38_P3 = 32,        /*!< fql38.p3 */
    MMAP_QL_FQL39_P3 = 33,        /*!< fql39.p3 */
    MMAP_QL_FQL4_P3 = 34,        /*!< fql4.p3 */
    MMAP_QL_FQL40_P3 = 35,        /*!< fql40.p3 */
    MMAP_QL_FQL41_P3 = 36,        /*!< fql41.p3 */
    MMAP_QL_FQL42_P3 = 37,        /*!< fql42.p3 */
    MMAP_QL_FQL43_P3 = 38,        /*!< fql43.p3 */
    MMAP_QL_FQL44_P3 = 39,        /*!< fql44.p3 */
    MMAP_QL_FQL45_P3 = 40,        /*!< fql45.p3 */
    MMAP_QL_FQL46_P3 = 41,        /*!< fql46.p3 */
    MMAP_QL_FQL47_P3 = 42,        /*!< fql47.p3 */
    MMAP_QL_FQL48_P3 = 43,        /*!< fql48.p3 */
    MMAP_QL_FQL49_P3 = 44,        /*!< fql49.p3 */
    MMAP_QL_FQL5_P3 = 45,        /*!< fql5.p3 */
    MMAP_QL_FQL50_P3 = 46,        /*!< fql50.p3 */
    MMAP_QL_FQL51_P3 = 47,        /*!< fql51.p3 */
    MMAP_QL_FQL52_P3 = 48,        /*!< fql52.p3 */
    MMAP_QL_FQL6_P3 = 49,        /*!< fql6.p3 */
    MMAP_QL_FQL7_P3 = 50,        /*!< fql7.p3 */
    MMAP_QL_FQL8_P3 = 51,        /*!< fql8.p3 */
    MMAP_QL_FQL9_P3 = 52,        /*!< fql9.p3 */
};
