#include "fns_offline.h"

FnsOfflinePlayer::FnsOfflinePlayer()
    : FNS_SOUNDS({Lang::Sounds::P3_NS1,
                  Lang::Sounds::P3_NS2,
                  Lang::Sounds::P3_NS3,
                  Lang::Sounds::P3_NS4,
                  Lang::Sounds::P3_NS5,
                  Lang::Sounds::P3_NS6,
                  Lang::Sounds::P3_NS7,
                  Lang::Sounds::P3_NS8,
                  Lang::Sounds::P3_NS9,
                  Lang::Sounds::P3_NS10,
                  Lang::Sounds::P3_NS11,
                  Lang::Sounds::P3_NS12,
                  Lang::Sounds::P3_NS13,
                  Lang::Sounds::P3_NS14,
                  Lang::Sounds::P3_NS15,
                  Lang::Sounds::P3_NS16,
                  Lang::Sounds::P3_NS17,
                  Lang::Sounds::P3_NS18,
                  Lang::Sounds::P3_NS19,
                  Lang::Sounds::P3_NS20,
                  Lang::Sounds::P3_NS21,
                  Lang::Sounds::P3_NS22,
                  Lang::Sounds::P3_NS23,
                  Lang::Sounds::P3_NS24,
                  Lang::Sounds::P3_NS25,
                  Lang::Sounds::P3_NS26,
                  Lang::Sounds::P3_NS27,
                  Lang::Sounds::P3_NS28,
                  Lang::Sounds::P3_NS29,
                  Lang::Sounds::P3_NS30,
                  Lang::Sounds::P3_NS31,
                  Lang::Sounds::P3_NS32,
                  Lang::Sounds::P3_NS33,
                  Lang::Sounds::P3_NS34,
                  Lang::Sounds::P3_NS35,
                  Lang::Sounds::P3_NS36,
                  Lang::Sounds::P3_NS37,
                  Lang::Sounds::P3_NS38,
                  Lang::Sounds::P3_NS39,
                  Lang::Sounds::P3_NS40,
                  Lang::Sounds::P3_NS41,
                  Lang::Sounds::P3_NS42,
                  Lang::Sounds::P3_NS43,
                  Lang::Sounds::P3_NS44,
                  Lang::Sounds::P3_NS45,
                  Lang::Sounds::P3_NS46,
                  Lang::Sounds::P3_NS47,
                  Lang::Sounds::P3_NS48,
                  Lang::Sounds::P3_NS49,
                  Lang::Sounds::P3_NS50,
                  Lang::Sounds::P3_NS51,
                  Lang::Sounds::P3_NS52,
                  Lang::Sounds::P3_NS53,
                  Lang::Sounds::P3_NS54,
                  Lang::Sounds::P3_NS55,
                  Lang::Sounds::P3_NS56,
                  Lang::Sounds::P3_NS57,
                  Lang::Sounds::P3_NS58,
                  Lang::Sounds::P3_NS59,
                  Lang::Sounds::P3_NS60,
                  Lang::Sounds::P3_NS61,
                  Lang::Sounds::P3_NS62,
                  Lang::Sounds::P3_NS63,
                  Lang::Sounds::P3_NS64,
                  Lang::Sounds::P3_NS65,
                  Lang::Sounds::P3_NS66,
                  Lang::Sounds::P3_NS67,
                  Lang::Sounds::P3_NS68,
                  Lang::Sounds::P3_NS69,
                  Lang::Sounds::P3_NS70,
                  Lang::Sounds::P3_NS71,
                  Lang::Sounds::P3_NS72,
                  Lang::Sounds::P3_NS73,
                  Lang::Sounds::P3_NS74,
                  Lang::Sounds::P3_NS75,
                  Lang::Sounds::P3_NS76,
                  Lang::Sounds::P3_NS77,
                  Lang::Sounds::P3_NS78,
                  Lang::Sounds::P3_NS79,
                  Lang::Sounds::P3_NS80,
                  Lang::Sounds::P3_NS81,
                  Lang::Sounds::P3_NS82,
                  Lang::Sounds::P3_NS83,
                  Lang::Sounds::P3_NS84,
                  Lang::Sounds::P3_NS85,
                  Lang::Sounds::P3_NS86,
                  Lang::Sounds::P3_NS87,
                  Lang::Sounds::P3_NS88,
                  Lang::Sounds::P3_NS89,
                  Lang::Sounds::P3_NS90,
                  Lang::Sounds::P3_NS91,
                  Lang::Sounds::P3_NS92,
                  Lang::Sounds::P3_NS93,
                  Lang::Sounds::P3_NS94,
                  Lang::Sounds::P3_NS95,
                  Lang::Sounds::P3_NS96,
                  Lang::Sounds::P3_NS97,
                  Lang::Sounds::P3_NS98,
                  Lang::Sounds::P3_NS99,
                  Lang::Sounds::P3_NS100,
                  Lang::Sounds::P3_NS101}) {}

const std::vector<std::string_view> &FnsOfflinePlayer::getSounds() const
{
    return FNS_SOUNDS;
}

const std::string_view FnsOfflinePlayer::getHelloSound() const
{
    return Lang::Sounds::P3_FNS;
}

const char* FnsOfflinePlayer::get_tag()  const
{
    return "Fns";
}