

#define ENABLE_SENSOR false
#ifdef CONFIG_BOX_LLM_WIFI

#define CONFIG_TOUCH1 (TOUCH_PAD_NUM1)
#define CONFIG_TOUCH2 (TOUCH_PAD_NUM8)
#define CONFIG_HUG_CHANNEL (ADC_CHANNEL_1)
#define CONFIG_LEFT_HAND (21)
#define CONFIG_RIGHT_HAND (-1)
#define CONFIG_SENSOR_LED (42)
#elif CONFIG_BOARD_HUG_BEAT_WIFI

#define CONFIG_TOUCH1 (TOUCH_PAD_NUM3)
#define CONFIG_TOUCH2 (TOUCH_PAD_NUM8)
#define CONFIG_HUG_CHANNEL (ADC_CHANNEL_9)
#define CONFIG_LEFT_HAND (14)
#define CONFIG_RIGHT_HAND (13)

#define CONFIG_SENSOR_LED (45)

#elif CONFIG_BOARD_TYPE_PPYUE_1_0_WIFI
#define CONFIG_TOUCH1 (TOUCH_PAD_NUM10)
#define CONFIG_TOUCH2 (TOUCH_PAD_NUM9)
#define CONFIG_HUG_CHANNEL (ADC_CHANNEL_7)
#define CONFIG_LEFT_HAND (21)
#define CONFIG_RIGHT_HAND (-1)
#define CONFIG_SENSOR_LED (16)

#endif